site_name: "FRINK OKN"
theme:
  name: material
  palette:
    scheme: default
    primary: light blue
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.indexes
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Quick Start Guide:
    - help/index.md
    - Setup Your FRINK Repo in the Landing Zone: help/setup.md
    - Update Your Graph in FRINK: help/update.md
    - Query knowledge graphs in FRINK: help/query-page.md
  - KG Authoring Guidance:
    - guidance/index.md
  - The Open Knowledge Network:
    - okn/index.md
    - Knowledge Graph (KG) Dataset Status: okn/kgstatus.md
    - Setup Your FRINK Repo in the Landing Zone: help/setup.md
    - Update Your Graph in FRINK: help/update.md
    - Query FRINK: https://frink.apps.renci.org
site_url: https://frink-okn.github.io
repo_url: https://github.com/frink-okn/frink-landing-zone/
