site_name: "FRINK OKN"
theme:
  name: material
  custom_dir: material
  logo: assets/images/frink.png
  palette:
    scheme: default
    primary: custom
  font:
    text: Open Sans
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate #puts the page anchor links on the left, instead of the right
    - navigation.indexes
extra_css:
  - styles.css
plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true     
nav:
  - Home: index.md
  - Quick Start Guide:
    - help/index.md
    - Setup Your FRINK Repo in the Landing Zone: help/setup.md
    - Update Your Graph in FRINK: help/update.md
    - Query knowledge graphs in FRINK: help/query-page.md
  - Best Practices:
    - guidance/index.md
  - The OKN Registry:
    - registry/index.md
    - Query FRINK: https://frink.apps.renci.org
site_url: https://frink-okn.github.io
repo_url: https://github.com/frink-okn/frink-landing-zone/

#     - Knowledge Graph (KG) Dataset Status: okn/kgstatus.md (add these links to the registry pages)
